
db:
  hosts:
    dbserver:
      ansible_host: 193.32.219.226

app:
  hosts:
    appserver:
      ansible_host: 217.28.230.196



# Example
#app:
#  hosts:
#    appserver:
#      ansible_host: 35.190.196.109

#db:
#  hosts:
#    dbserver:
#      ansible_host: 104.155.9.218
